### PR TITLE
maintaining the data in a JSON

### PR DESCRIPTION
**Pull request by stoeffel**
This is an initial PR to move the data to a JSON file and creating the README by running
`npm run create-readme` (it uses [doxie](https://github.com/studio-b12/doxie) for that).
This will allow us later to use the data in f.e. a CLI-tool.

Maybe we can even group the data. @tomekwi is this possible?

How do you like this @hemanth?

refs https://github.com/npm-scripts/meta/issues/2

### CODE REVIEW

**Comment by hemanth** [comment]
I have added you both as the owners to this org, lets level up this org :+1: 

Thanks.

**Comment by stoeffel** [comment]
Cool, thx!
Should we merge this and open an issue for grouping the data?

**Comment by hemanth** [comment]
Makes sense, merged it @stoeffel /me awaits @tomekwi

**Comment by tomek-he-him** [comment]
Wow, looks great! :+1: 

Glad to see doxie at work! :)

**Comment by tomek-he-him** [comment]
Thanks @hemanth! I have some wild npm scripts out there – I’ll open a PR in a while.

**Comment by hemanth** [comment]
Cool @tomekwi :+1:

**Comment by tomek-he-him** [comment]
@stoeffel two more things I’ve noticed:
- An apostrophe [gets lost](https://github.com/npm-scripts/scripts/tree/679d026acd04a2ce26f101ec9aa536989017c065#minor-release) in every script. Should be `"minor-release":`
- A `"\n"` becomes [a line break](https://github.com/npm-scripts/scripts/tree/679d026acd04a2ce26f101ec9aa536989017c065#clean-up).

**Comment by tomek-he-him** [comment]
Oh and
- A `\"` becomes a `"` [here](https://github.com/npm-scripts/scripts/tree/921a7a9ce3e528535ef1d4ecedacd2aa1e3fde76#ensure-clean-repo).

**Comment by stoeffel** [comment]
@tomekwi good catch. we should escape the strings.

> An apostrophe gets lost in every script. Should be "minor-release":

I fixed that.

**Pull request merged**
