### PR TITLE
Add `ensure-clean-repo`

### PR DESCRIPTION
**Pull request by tomek-he-him**
## ensure-clean-repo

Ensure there are no uncommitted files in your git repo. Otherwise fail with a helpful message.

``` json
"scripts": {
  "ensure-clean-repo": "if [ -n \"$(git status --porcelain)\" ]; then echo 'Ooops-a-daisy! Make sure the repo is clean.'; exit 1; fi"
}
```

### CODE REVIEW

**Comment by tomek-he-him** [comment]
I’ve rebased to include all recent updates by @stoeffel.

By the way, this script depends on bash. Do you guys have any clue how to make it cross-shell?

**Comment by hemanth** [comment]
There is no straight forward way but check `$SHELL` and change the code accordingly or use something like `shelljs` for now we could stick to `bash` :)?

**Comment by tomek-he-him** [comment]
Yeah, but putting js into npm scripts makes the thing even more messy.

**Comment by tomek-he-him** [comment]
Closing to remove clutter 🙂

Feel free to open if you think this is mergeable.

**Pull request closed without merging**
