### PR TITLE
add script to create toc and to create all

### PR DESCRIPTION
**Pull request by stoeffel**
adds `npm run generate` and `npm run create-toc`

### CODE REVIEW

**Comment by stoeffel** [comment]
@tomekwi is there a way to add a newline after the last content between the `inject`-tags?
To avoid this:

screen shot 2015-07-06 at 20 17 14

maybe we could add a custom footer/header to doxie.inject or a beforeAll afterAll option.

**Comment by tomek-he-him** [comment]
So far nothing was added. I treated newline as many Unix programs – as End Of Line. So if your docs end with a newline, there is a newline.

But I guess I’ll add a check for that – and if the docs don’t end with a newline, I’ll add one. I think `cat` does the same thing.

**Comment by tomek-he-him** [comment]
beforeAll and afterAll could be another plugin. It’s very simple to do, just emit some docs at the beginning or end, like:

``` js
{
  output: "This will be at the end"
}
```

**Comment by stoeffel** [comment]
:checkered_flag:

**Comment by stoeffel** [comment]
Two commits from @tomekwi sneaked there way in there. Do you guys mind??? Otherwise this is good to go and can be changed later to remove the list/newline workaround.

**Comment by tomek-he-him** [comment]
Looks great to me!

**Comment by stoeffel** [comment]
hmmm... I don't like the index approach. I think the only usecase is to inser content before or after the rendered content.
`--insert '\n' afterContent`

**Comment by tomek-he-him** [comment]
Then we’ll start minimal. Just `--insert '\n'`. It’s easy to add options later, harder to take them away.

**Comment by stoeffel** [comment]
> Then we’ll start minimal. Just --insert '\n'. It’s easy to add options later, harder to take them away.

SGTM

**Comment by stoeffel** [comment]
will rebase once again asap. :smile_cat:

**Comment by stoeffel** [comment]
rebased. can we merge this? @npm-scripts/owners

**Comment by hemanth** [comment]
Done :+1: 

Thank you!

**Comment by tomek-he-him** [comment]
@stoeffel @hemanth I’ve made [doxie.append](https://github.com/studio-b12/doxie.append) today. Here’s the thing at work: https://github.com/studio-b12/mve/blob/b1d7209/package.json#L17.

**Comment by hemanth** [comment]
Nice, is there any way to avoid that `echo '[]' |` ?

**Comment by tomek-he-him** [comment]
At the moment not :(. doxie expects a JSON array over stdin – so if you call it without passing a string it switches into interactive input.

There is one reasonable option to prevent this – write another CLI for doxie-core which pipes an empty array into it.

**Comment by hemanth** [comment]
:8ball:

**Pull request merged**
