### PR TITLE
Fix releases

### PR DESCRIPTION
**Pull request by jamiebuilds**

### CODE REVIEW

**Comment by hemanth** [comment]
Thanks!

**Comment by hemanth** [comment]
@thejameskyle Added you the org (:

**Comment by stoeffel** [comment]
@thejameskyle welcome to the org :+1:

**Comment by stoeffel** [comment]
@thejameskyle @hemanth This change will be reset when we next time run `npm run generate`. all changes shiuld be done in the scripts.json. Maybe we should add a contributing.md.

**Comment by jamiebuilds** [comment]
> This change will be reset when we next time run npm run generate. all changes shiuld be done in the scripts.json.

Whoops, sorry I was just editing the file directly on GitHub. I'll fix that

**Comment by stoeffel** [comment]
np. It isn't clear without instruction :smiley:

**Comment by hemanth** [comment]
I didn't noticed the change was in `readme` yikes, yeah as @stoeffel mentioned.

**Pull request merged**
