### PR TITLE
Keep the scripts diffy

### PR DESCRIPTION
**Pull request by tomek-he-him**
Why: it’s easier to merge, rebase and reorder.

Another option: use YAML or CSON instead of JSON.

### CODE REVIEW

**Comment by stoeffel** [comment]
I don't really like this format. I think it makes the file less readable.

> Another option: use YAML or CSON instead of JSON.

:+1: but I would generate a json for usage in other tools.

and :+1: for YAML

**Comment by hemanth** [comment]
YAML is also fine in this case :)

**Comment by tomek-he-him** [comment]
Closing to remove clutter 🙂

Feel free to open if you think this is mergeable.

**Comment by tomek-he-him** [comment]
I don’t think this is a good idea anymore 😁

**Pull request closed without merging**
